version: "3.5"

services:
    db:
        image: postgres:10-alpine
        container_name: db-pg
        restart: always
        volumes:
          - ./data/postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=web_db
          - POSTGRES_USER=pttapp
          - POSTGRES_PASSWORD=pttapp
        ports:
            - "5555:5432"
        networks:
          - proxy

    rabbitmq:
        image: rabbitmq:3-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=rmq
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_DEFAULT_VHOST=my_vhost
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
          - proxy
    worker:
        build: ./webapp
        restart: always
        depends_on:
          - rabbitmq
          - db
        entrypoint: celery -A webapp worker -l INFO -Q period
        volumes:
          - ./webapp:/src
        environment:
          - WEBAPP_ENV=dev
          - POSTGRES_HOST=db-pg
          - POSTGRES_DB=web_db
          - POSTGRES_USER=pttapp
          - POSTGRES_PASSWORD=pttapp
          - BROKER_DSN=pyamqp://rmq:password@rabbitmq/my_vhost
        networks:
          - proxy

    web:
        build: ./webapp
        restart: always
        ports:
          - "5010:8080"
        volumes:
          - ./webapp:/src
        environment:
          - WEBAPP_ENV=production
          - POSTGRES_HOST=db-pg
          - POSTGRES_DB=web_db
          - POSTGRES_USER=pttapp
          - POSTGRES_PASSWORD=pttapp
          - BROKER_DSN=pyamqp://rmq:password@rabbitmq/my_vhost
        depends_on:
          - rabbitmq
          - db
        networks:
          - proxy

networks:
    proxy:

